2018-04-04 11:43:40,036 INFO: Microblog start up [in C:\Users\Wilson Wang\Desktop\Flask\microblog\app\__init__.py:51]
2018-04-04 11:43:50,888 ERROR: Exception on /login [POST] [in d:\python2.7\lib\site-packages\flask\app.py:1560]
Traceback (most recent call last):
  File "d:\python2.7\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\python2.7\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\python2.7\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python2.7\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\python2.7\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Wilson Wang\Desktop\Flask\microblog\app\routes.py", line 48, in login
    flash(_('Invalid username or password'))
  File "d:\python2.7\lib\site-packages\flask_babel\__init__.py", line 552, in gettext
    t = get_translations()
  File "d:\python2.7\lib\site-packages\flask_babel\__init__.py", line 227, in get_translations
    [get_locale()],
  File "d:\python2.7\lib\site-packages\flask_babel\__init__.py", line 257, in get_locale
    rv = babel.locale_selector_func()
  File "C:\Users\Wilson Wang\Desktop\Flask\microblog\app\__init__.py", line 55, in get_locale
    return request.accept_languages.best_match(app.config['LANGUAGES'])
NameError: global name 'request' is not defined
2018-04-04 11:44:45,421 INFO: Microblog start up [in C:\Users\Wilson Wang\Desktop\Flask\microblog\app\__init__.py:51]
2018-04-04 20:56:58,839 INFO: Microblog start up [in C:\Users\Wilson Wang\Desktop\Flask\microblog\app\__init__.py:71]
2018-04-04 20:57:03,038 ERROR: Exception on /index [GET] [in d:\python2.7\lib\site-packages\flask\app.py:1560]
Traceback (most recent call last):
  File "d:\python2.7\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\python2.7\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\python2.7\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python2.7\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\python2.7\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "d:\python2.7\lib\site-packages\flask_login.py", line 792, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\Wilson Wang\Desktop\Flask\microblog\app\main\routes.py", line 31, in index
    page, app.config['POSTS_PER_PAGE'], False)
NameError: global name 'app' is not defined
2018-04-08 17:16:19,374 INFO: Microblog start up [in C:\Users\Wilson Wang\Desktop\Flask\microblog\app\__init__.py:71]
2018-04-08 17:16:47,289 ERROR: Exception on /favicon.ico [GET] [in d:\python2.7\lib\site-packages\flask\app.py:1560]
Traceback (most recent call last):
  File "d:\python2.7\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\python2.7\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\python2.7\lib\site-packages\flask\app.py", line 1512, in handle_user_exception
    return self.handle_http_exception(e)
  File "d:\python2.7\lib\site-packages\flask\app.py", line 1471, in handle_http_exception
    return handler(e)
  File "C:\Users\Wilson Wang\Desktop\Flask\microblog\app\errors\handlers.py", line 7, in not_found_error
    return render_template('errors/404.html'), 404
  File "d:\python2.7\lib\site-packages\flask\templating.py", line 134, in render_template
    context, ctx.app)
  File "d:\python2.7\lib\site-packages\flask\templating.py", line 116, in _render
    rv = template.render(context)
  File "d:\python2.7\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "d:\python2.7\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Wilson Wang\Desktop\Flask\microblog\app\templates\errors\404.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\Wilson Wang\Desktop\Flask\microblog\app\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "d:\python2.7\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "d:\python2.7\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block "doc"
    {%- block html %}
  File "d:\python2.7\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block "html"
    {% block body -%}
  File "d:\python2.7\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 23, in block "body"
    {% block content -%}
  File "C:\Users\Wilson Wang\Desktop\Flask\microblog\app\templates\base.html", line 48, in block "content"
    {% block app_content %}{% endblock %}
  File "C:\Users\Wilson Wang\Desktop\Flask\microblog\app\templates\errors\404.html", line 5, in block "app_content"
    <p><a href="{{ url_for('index') }}">Back</a></p>
  File "d:\python2.7\lib\site-packages\flask\helpers.py", line 333, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "d:\python2.7\lib\site-packages\flask\app.py", line 1805, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "d:\python2.7\lib\site-packages\flask\helpers.py", line 323, in url_for
    force_external=external)
  File "d:\python2.7\lib\site-packages\werkzeug\routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
BuildError: Could not build url for endpoint 'index'. Did you mean 'main.index' instead?
2018-04-08 17:21:47,871 ERROR: Exception on /login [GET] [in d:\python2.7\lib\site-packages\flask\app.py:1560]
Traceback (most recent call last):
  File "d:\python2.7\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\python2.7\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\python2.7\lib\site-packages\flask\app.py", line 1512, in handle_user_exception
    return self.handle_http_exception(e)
  File "d:\python2.7\lib\site-packages\flask\app.py", line 1471, in handle_http_exception
    return handler(e)
  File "C:\Users\Wilson Wang\Desktop\Flask\microblog\app\errors\handlers.py", line 7, in not_found_error
    return render_template('errors/404.html'), 404
  File "d:\python2.7\lib\site-packages\flask\templating.py", line 134, in render_template
    context, ctx.app)
  File "d:\python2.7\lib\site-packages\flask\templating.py", line 116, in _render
    rv = template.render(context)
  File "d:\python2.7\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "d:\python2.7\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Wilson Wang\Desktop\Flask\microblog\app\templates\errors\404.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\Wilson Wang\Desktop\Flask\microblog\app\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "d:\python2.7\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "d:\python2.7\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block "doc"
    {%- block html %}
  File "d:\python2.7\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block "html"
    {% block body -%}
  File "d:\python2.7\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 23, in block "body"
    {% block content -%}
  File "C:\Users\Wilson Wang\Desktop\Flask\microblog\app\templates\base.html", line 48, in block "content"
    {% block app_content %}{% endblock %}
  File "C:\Users\Wilson Wang\Desktop\Flask\microblog\app\templates\errors\404.html", line 5, in block "app_content"
    <p><a href="{{ url_for('index') }}">Back</a></p>
  File "d:\python2.7\lib\site-packages\flask\helpers.py", line 333, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "d:\python2.7\lib\site-packages\flask\app.py", line 1805, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "d:\python2.7\lib\site-packages\flask\helpers.py", line 323, in url_for
    force_external=external)
  File "d:\python2.7\lib\site-packages\werkzeug\routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
BuildError: Could not build url for endpoint 'index'. Did you mean 'main.index' instead?
